# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsedtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lap',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.Player'),
        ),
    ]
